name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: export PYTHONPATH=$PYTHONPATH:$(pwd)
    
    - name: Run tests with coverage
      run: |
        pytest --cov=myapp --cov-report=term > tests/coverage.txt

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: tests/coverage.txt

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build application
        run: echo "Building application..."

      - name: Update README with build badge
        run: |
          BADGE="[![Build Status](https://github.com/Andriy29k/GitActions_task2/actions/workflows/test.yml/badge.svg)](https://github.com/Andriy29k/GitActions_task2/actions/workflows/test.yml)"
          README="README.md"
      
          if grep -q "\[!\[Build Status\]" "$README"; then
            echo "Badge already exists in $README"
          else
            echo "Updating $README with badge..."
            echo "$BADGE" >> "$README"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}