- name: Update README with build badge
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    STATUS=$(curl -H "Authorization: token $GITHUB_TOKEN" \
    -s https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r '.conclusion')
    BADGE="[![Build Status](https://github.com/${{ github.repository }}/actions/workflows/test.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/test.yml)"
    README="README.md"
    if grep -q "\[!\[Build Status\]" $README; then
      echo "Badge already exists in README.md"
    else
      echo "Updating README.md with badge..."
      echo "$BADGE" >> $README
    fi